{{- if .Values.rbac.namespaceAdmin.enabled }}
{{- if eq .Values.users.mode "generate" }}
{{- range $i := until (.Values.users.generate.count | int) }}
{{- $userNum := add ($.Values.users.generate.startNumber | int) $i }}
{{- $username := printf "%s%d-%s" $.Values.users.generate.prefix $userNum $.Values.tenant.guid }}
{{- $nsNum := add ($.Values.namespaces.generate.startNumber | int) $i }}
{{- $nsName := printf "%s%d-%s%s" $.Values.namespaces.generate.prefix $nsNum $.Values.tenant.guid $.Values.namespaces.generate.suffix }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $username }}-{{ $.Values.rbac.namespaceAdmin.clusterRole }}
  namespace: {{ $nsName }}
  labels:
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/component: tenant
    app.kubernetes.io/instance: {{ $.Values.tenant.guid }}
    tenant-guid: {{ $.Values.tenant.guid | quote }}
    tenant-user: {{ $username | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $.Values.rbac.namespaceAdmin.clusterRole }}
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: {{ $username }}
{{- end }}
{{- else if eq .Values.users.mode "explicit" }}
{{- range $idx, $username := .Values.users.explicit.usernames }}
{{- $fullUsername := printf "%s-%s" $username $.Values.tenant.guid }}
{{- $nsName := "" }}
{{- if eq $.Values.namespaces.mode "explicit" }}
{{- $nsName = printf "%s-%s" (index $.Values.namespaces.explicit.names $idx) $.Values.tenant.guid }}
{{- else }}
{{- $nsNum := add ($.Values.namespaces.generate.startNumber | int) $idx }}
{{- $nsName = printf "%s%d-%s%s" $.Values.namespaces.generate.prefix $nsNum $.Values.tenant.guid $.Values.namespaces.generate.suffix }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $fullUsername }}-{{ $.Values.rbac.namespaceAdmin.clusterRole }}
  namespace: {{ $nsName }}
  labels:
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/component: tenant
    app.kubernetes.io/instance: {{ $.Values.tenant.guid }}
    tenant-guid: {{ $.Values.tenant.guid | quote }}
    tenant-user: {{ $fullUsername | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $.Values.rbac.namespaceAdmin.clusterRole }}
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: {{ $fullUsername }}
{{- end }}
{{- end }}
{{- end }}
