{{- if .Values.keycloak.route.enabled }}
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: keycloak
  namespace: {{ .Values.namespace }}
spec:
  host: {{ .Values.keycloak.hostname }}.{{ .Values.keycloak.ingressDomain }}
  to:
    kind: Service
    name: keycloak
    weight: 100
  port:
    targetPort: https
  tls:
    termination: {{ .Values.keycloak.route.tls.termination }}
    insecureEdgeTerminationPolicy: {{ .Values.keycloak.route.tls.insecureEdgeTerminationPolicy }}
  wildcardPolicy: None
{{- end }}
