{{- if eq .Values.users.mode "generate" }}
{{- if gt (.Values.users.generate.count | int) 0 }}
{{- range $i := until (.Values.users.generate.count | int) }}
{{- $userNum := add ($.Values.users.generate.startNumber | int) $i }}
{{- $username := printf "%s%d-%s" $.Values.users.generate.prefix $userNum $.Values.tenant.guid }}
---
apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakUser
metadata:
  name: {{ $username }}
  namespace: {{ $.Values.keycloak.namespace }}
  labels:
    app.kubernetes.io/name: keycloak-users
    app.kubernetes.io/component: tenant
    app.kubernetes.io/instance: {{ $.Values.tenant.guid }}
    tenant-guid: {{ $.Values.tenant.guid | quote }}
    tenant-user: "true"
spec:
  realmName: {{ $.Values.keycloak.realmName }}
  user:
    username: {{ $username }}
    enabled: true
    emailVerified: {{ $.Values.users.emailVerified }}
    email: {{ $username }}@{{ $.Values.users.emailDomain }}
    firstName: {{ $.Values.users.firstName }}{{ $userNum }}
    lastName: {{ $.Values.users.lastName }}
    credentials:
      - type: password
        value: {{ $.Values.users.password }}
        temporary: {{ $.Values.users.temporary }}
    {{- if $.Values.users.realmRoles }}
    realmRoles:
      {{- toYaml $.Values.users.realmRoles | nindent 6 }}
    {{- end }}
    {{- if $.Values.users.groups }}
    groups:
      {{- toYaml $.Values.users.groups | nindent 6 }}
    {{- end }}
    {{- if $.Values.attributes }}
    attributes:
      {{- range $key, $value := $.Values.attributes }}
      {{ $key }}:
        - {{ tpl ($value | toString) $ | quote }}
      {{- end }}
    {{- end }}
{{- end }}
{{- end }}
{{- else if eq .Values.users.mode "explicit" }}
{{- if .Values.users.explicit.usernames }}
{{- range $username := .Values.users.explicit.usernames }}
{{- $fullUsername := printf "%s-%s" $username $.Values.tenant.guid }}
---
apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakUser
metadata:
  name: {{ $fullUsername }}
  namespace: {{ $.Values.keycloak.namespace }}
  labels:
    app.kubernetes.io/name: keycloak-users
    app.kubernetes.io/component: tenant
    app.kubernetes.io/instance: {{ $.Values.tenant.guid }}
    tenant-guid: {{ $.Values.tenant.guid | quote }}
    tenant-user: "true"
spec:
  realmName: {{ $.Values.keycloak.realmName }}
  user:
    username: {{ $fullUsername }}
    enabled: true
    emailVerified: {{ $.Values.users.emailVerified }}
    email: {{ $fullUsername }}@{{ $.Values.users.emailDomain }}
    firstName: {{ $username | title }}
    lastName: {{ $.Values.users.lastName }}
    credentials:
      - type: password
        value: {{ $.Values.users.password }}
        temporary: {{ $.Values.users.temporary }}
    {{- if $.Values.users.realmRoles }}
    realmRoles:
      {{- toYaml $.Values.users.realmRoles | nindent 6 }}
    {{- end }}
    {{- if $.Values.users.groups }}
    groups:
      {{- toYaml $.Values.users.groups | nindent 6 }}
    {{- end }}
    {{- if $.Values.attributes }}
    attributes:
      {{- range $key, $value := $.Values.attributes }}
      {{ $key }}:
        - {{ tpl ($value | toString) $ | quote }}
      {{- end }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}
