---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: this
    targetRevision: main
    path: 3scale
    helm:
      # valueFiles:
      #   - values-apis.yaml
      values: |
        namespace: 3scale
        operator:
          channel: threescale-2.14
          startingCSV: 3scale-operator.x.y.z
          installPlanApproval: Manual
        apimanager:
          wildcardDomain: apps.cluster.opentlc.com
          tenantName: demo
          llmMetrics:
            name: llm-metrics
            version: 0.1
        helper-status-checker:
          approver: true
          checks:
            - operatorName: 3scale-operator
              namespace:
                name: 3scale
              syncwave: '1'
              serviceAccount:
                name: "3scale-status-checker"
  destination:
    server: https://kubernetes.default.svc
    namespace: 3scale
