---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-pgsql-user
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  dbname: {{ .Values.postgresql.database.name }}
  host: keycloak-pgsql.{{ .Values.namespace }}.svc
  port: "{{ .Values.postgresql.service.port }}"
  user: {{ .Values.postgresql.database.user }}
  password: {{ .Values.postgresql.database.password }}
