---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhoai
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: this
    targetRevision: main
    path: rhoai
    helm:
      values: |
        operator:
          startingCSV: rhods-operator.x.y.z
          installPlanApproval: Manual
        patcher:
          dashboard:
            replicas: 1
        helper-status-checker:
          approver: false
  destination:
    server: https://kubernetes.default.svc

