{{- if eq .Values.namespaces.mode "generate" }}
{{- range $i := until (.Values.namespaces.generate.count | int) }}
{{- $num := add ($.Values.namespaces.generate.startNumber | int) $i }}
{{- $nsName := printf "%s%d-%s%s" $.Values.namespaces.generate.prefix $num $.Values.tenant.guid $.Values.namespaces.generate.suffix }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $nsName }}
  labels:
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/component: tenant
    app.kubernetes.io/instance: {{ $.Values.tenant.guid }}
    tenant-guid: {{ $.Values.tenant.guid | quote }}
    {{- if $.Values.namespaces.labels }}
    {{- toYaml $.Values.namespaces.labels | nindent 4 }}
    {{- end }}
  {{- if $.Values.namespaces.annotations }}
  annotations:
    {{- toYaml $.Values.namespaces.annotations | nindent 4 }}
  {{- end }}
{{- end }}
{{- else if eq .Values.namespaces.mode "explicit" }}
{{- range $name := .Values.namespaces.explicit.names }}
{{- $nsName := printf "%s-%s" $name $.Values.tenant.guid }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $nsName }}
  labels:
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/component: tenant
    app.kubernetes.io/instance: {{ $.Values.tenant.guid }}
    tenant-guid: {{ $.Values.tenant.guid | quote }}
    {{- if $.Values.namespaces.labels }}
    {{- toYaml $.Values.namespaces.labels | nindent 4 }}
    {{- end }}
  {{- if $.Values.namespaces.annotations }}
  annotations:
    {{- toYaml $.Values.namespaces.annotations | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
